/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'jeff' at '3/16/15 9:01 PM' with Gradle 2.3
 *
 * @author jeff, @date 3/16/15 9:01 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
